#numpy
#NUMERICAL PYTHON
this is a pyhton library for working with arrays 
it has functions for working with linear algebra ,fourier transfformation and martrices 


In [1]:
import numpy
arr=numpy.array([1,2,3,4,5])#syntax for an array
print(arr)

[1 2 3 4 5]


In [2]:
#you can import it with an alias name '
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
#checking for the version
import numpy as n
print("ths is version",n.__version__)

ths is version 1.20.1


In [8]:
'''
the array object in numpy is called ndarray
the ndarray can be created using the array()->function
-to create an ndarray we can pass in a tuple ,list or array like object
'''
import numpy as n 
arr_list=n.array([1,2,3,4,5])
arr_tuple=n.array((1,2,3,4,5))
print(arr_list)
print(arr_tuple)
print(type(arr))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


#0-Darrays
import numpy as np
arr=np.array(42)
print(arr)

In [17]:
#1-Darrays
#2-Darray
#3-Darray
import numpy as np
arr=np.array([1,2,3,4])
arr_2=np.array([[1,2,3],[4,5,6]])
arr_3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
#checking for the dimensions
#use the ndim attribute that returns an int that tells as how many dimensions we are working with
print(arr.ndim)
print(arr_2.ndim)
print(arr_3.ndim)
#Higher dimension arrays 
#an array can have any number of dimensions 
#wecan create an array of 5 dimensions 
import numpy as np
arr_higher=np.array([1,2,3,4,5],ndmin=5)
#just initilize ndim with a value which is your dimension
#difine the number if dimensions with ndmin argument 
print(arr)

1
2
3
[1 2 3 4]


In [28]:
#acccessing array elements 
'''
the values in the array can be accessed using indexing 
access the value by reffering to  its index 
the index in nupy start with index zero

'''
arr=np.array([1,2,3,4])
print(arr[0],arr[1],arr[2],arr[3])#one dim arrays 
arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2[0],arr_2[1],arr_2[0,0],arr_2[0,1],arr_2[0,2],arr_2[1,0],arr_2[1,1],arr_2[1,2])#two dim array 
arr_3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr_3[0],arr_3[1],arr_3[0,0,2])

1 2 3 4
[1 2 3] [4 5 6] 1 2 3 4 5 6
[[1 2 3]
 [4 5 6]] [[1 2 3]
 [4 5 6]] 3


In [36]:
#SLICING
'''SLICING IN PYTHON MEANS TAKING AN ELEMENT 
    FORM ONE GIVEN INDEX TO ANOTHER GIVEN INDEX 
    [START:STOP] OR [START:STOP:STEP]

'''
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1:5])#gets values from  index one to 5
print(arr[1:])#form index 1 to the end of the list
print(arr[4:])
print(arr[:4])#form the start of the list to the end 
#negative slicing 
print(arr[-3:-1])
#step
print(arr[::2])
print(arr[2::2])

[2 3 4 5]
[2 3 4 5]
[5]
[1 2 3 4]
[3 4]
[1 3 5]
[3 5]


In [40]:
#SLICING 2D ARRAYS
'''
syntax{
    arr[element,start:stop:step]
            or
    arr[start:stop:step , start:stop:step]        
}
'''
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1:4])
print(arr[1,0:])
print(arr[0:2 ,0:2])

[2 3]
[4 5 6]
[[1 2]
 [4 5]]


In [2]:
'''
datatypes in python
strings -text data 
integers ->int nmbers 
float->real numbers 
booloean->true false
complex ->complex numbers 
i integer
u unsigned integers
b boolean
u unsigned integer
f float
c comlex float 
m timedelta 
M datetime
O object 
S string
U unicode string 
V fixed chunk of memeory for other type void 


'''
import numpy as np 
arr=np.array([1,2,3,4] ,dtype="i")
#dtype can be sued to specify the type of int 
arr_two=np.array(["banan","mango"])
print(arr_two.dtype)
print(arr.dtype)

<U5
int32


#CONVERTING DATA TYPE ON EXISTING ARRAYS 

In [9]:
'''
The best way to change the datatype of an existing array is to make a copy 
of the array with the astype() mathod 
astype ()allows as to create a copy of an array and allows as to specify 
teh data type as a parameter 
data types can be specified using a string like 'f' for float'i' for integer 

'''
import numpy as np 
arr = np.array([1.1,2.2,0])#float
new_arr=arr.astype('i')#change to integer
sec_arr=new_arr.astype(bool)
print(new_arr)
print(sec_arr)#returns true when the values are one and above 
print(sec_arr.dtype)

[1 2 0]
[ True  True False]
bool


THE DIFFRENCE BTWN COPY AND VIEW 
    The main difference between a copy and a view of an array 
    is that the copy is a new array and the view is just a viewof the original 
    array 
    The copy owns the data and any changes made to the copy will not affect the 
    original array 
    The view does not own the data and any changes made to the view will affect 
    the original array and any changes made to the original array will affect the view
    

In [11]:
import numpy as np 
arr = np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)#changes occured hereonly 
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [12]:
import numpy as np 
arr = np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)
#both arrays were affected 

[42  2  3  4  5]
[42  2  3  4  5]


In [13]:
'''
we can be able to show how the array in  py owns its data 
every numpy array has the attribute base thatreturns None 
if the array owns the data 
'''
import numpy as np 
arr = np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)#returns none showing that it owns the data 
print(y.base)#the view returns the origiinal array 

None
[1 2 3 4 5]


NUMPY ARRAY SHAPE
    the shape of an array is the number of elements in each dimensions 
    GET THE SHAPE OF AN ARRAY 
        Numpy arrays have an attribute called shape 
        that returns a tuple with each index having 
        the number of corresponding elements 
         
    

In [32]:
import numpy as np 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim,"dimensions")
print(arr)

(2, 4)
2 dimensions
[[1 2 3 4]
 [5 6 7 8]]


In [29]:
#create a 5th dimension 
import numpy as n 
arr=np.array([1,2,3,4],ndmin=5);
print(arr)

[[[[[1 2 3 4]]]]]


In [10]:
'''
RESHAPING ARRAYS 
    Reshape form 1-d to 2-d

'''
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr=arr.reshape(4,3)
arr_3d=arr.reshape(2,3,2)#2 rows 3 cols and 
print(arr_3d)
#print(newarr)
#the folllowing is a view sinceit returns the original array
print(arr_3d.base)#returns the original array -->its aview 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
#flattening an array
'''
this means converting a multi dimensional 
array intoa 1d array ....we can use reshape to do this 
'''
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


#ITERATING AN ARRAY


In [16]:
import numpy as np 
arr= np.array([1,2,3])
for _ in arr:
    print(_)

1
2
3


In [20]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
for _ in arr:
    #applies when iterating only rows
    print(_)
#when iterating rows and columns neat the for loops 
for row in arr:
    for col in row:
        print(col)    

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [22]:
#iterating 3d arrays
import numpy as np 

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for a in arr:
    for b in a:
        for c in b:
            print (c)#gets the indivitual values 

1
2
3
4
5
6
7
8
9
10
11
12
